<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>aae815df-3a30-4593-ae8d-77629fbc7241</testSuiteGuid>
   <testCaseLink>
      <guid>6a3446a0-71c0-4950-97c9-99e16ab81c9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CallTestCases/LoginWithValidUserNameAndPassword</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b151baa7-1a16-4a95-8f55-0cc4833a0ee9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login_Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1683a299-2449-4c2f-bb45-6b0a7d301258</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa7e1696-fe16-4b24-8cdc-c913657ab0ab</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
